In [214]:
import numpy as np

M = 3
N = 3

table = np.random.randint(100, size=(M,N))

In [215]:
table

array([[80, 85, 25],
       [96, 62, 13],
       [75, 56, 43]])

In [216]:
table[2]

array([75, 56, 43])

In [217]:
table[:3,2:3]

array([[25],
       [13],
       [43]])

In [218]:
table[-1] = 7

In [219]:
table

array([[80, 85, 25],
       [96, 62, 13],
       [ 7,  7,  7]])

In [220]:
table[:, -1]= table[:,0:-1].sum(axis = 1)

print(table)

[[ 80  85 165]
 [ 96  62 158]
 [  7   7  14]]
